### ISSUE TITLE
Doesn't working

### ISSUE THREAD

**Issue by sohate** [eiskrenkov/alfred-run-shortcut#1]
Hello! Type "sc" - nothing happens. What's mean "It also requires `shortcuts` executable to be available in system."?

**Comment by eiskrenkov** [comment]
Hey, @sohate, what version of macOS do you use and do you have Shortcuts app installed? If shortcuts app is installed - could you please enable debugger in Alfred, type sc once again and send me logs? :)

![Screen Shot 2021-11-07 at 18 27 24](https://user-images.githubusercontent.com/39211838/140651386-c6e51eb1-e5b6-4e24-8f44-ccce25b9bb9e.png)

**Comment by sohate** [comment]
MacOS 12.0.1. Yes, Shortcut app installed. Here's screenshot of debugging:

https://ibb.co/TW74xT9

**Comment by eiskrenkov** [comment]
@sohate there is a file for unreleased v0.2.0 - [Run Shortcut v0.2.0.zip](https://github.com/eiskrenkov/alfred-run-shortcut/files/7492596/Run.Shortcut.v0.2.0.zip)

Could you please test this and tell me if issue is fixed for you, please? :)

**Comment by sohate** [comment]
Yes, now it's working. Thanks!

**Comment by eiskrenkov** [comment]
Thanks you! Closing this issue and creating the release then
